import type { ProviderInfo } from './types.js';

export const PROVIDERS: ProviderInfo[] = [
  {
    id: 'openai',
    displayName: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'gpt-5.2', displayName: 'GPT-5.2' },
      { id: 'gpt-5-mini', displayName: 'GPT-5 Mini' },
      { id: 'gpt-5-nano', displayName: 'GPT-5 Nano' },
      { id: 'gpt-4.1', displayName: 'GPT-4.1' },
      { id: 'gpt-4.1-mini', displayName: 'GPT-4.1 Mini' },
      { id: 'gpt-4.1-nano', displayName: 'GPT-4.1 Nano' },
      { id: 'o4-mini', displayName: 'o4-mini' },
    ],
  },
  {
    id: 'anthropic',
    displayName: 'Anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    requiresApiKey: true,
    isOpenAICompatible: false,
    models: [
      { id: 'claude-opus-4-6', displayName: 'Claude Opus 4.6' },
      { id: 'claude-sonnet-4-6', displayName: 'Claude Sonnet 4.6' },
      { id: 'claude-haiku-4-5-20251001', displayName: 'Claude Haiku 4.5' },
    ],
  },
  {
    id: 'google',
    displayName: 'Google (Gemini)',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    requiresApiKey: true,
    isOpenAICompatible: false,
    models: [
      { id: 'gemini-3.1-pro-preview', displayName: 'Gemini 3.1 Pro' },
      { id: 'gemini-3-pro-preview', displayName: 'Gemini 3 Pro' },
      { id: 'gemini-3-flash-preview', displayName: 'Gemini 3 Flash' },
      { id: 'gemini-2.5-pro', displayName: 'Gemini 2.5 Pro' },
      { id: 'gemini-2.5-flash', displayName: 'Gemini 2.5 Flash' },
      { id: 'gemini-2.5-flash-lite', displayName: 'Gemini 2.5 Flash Lite' },
    ],
  },
  {
    id: 'xai',
    displayName: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'grok-4', displayName: 'Grok 4' },
      { id: 'grok-4-fast-reasoning', displayName: 'Grok 4 Fast (Reasoning)' },
      { id: 'grok-4-fast-non-reasoning', displayName: 'Grok 4 Fast (Instant)' },
      { id: 'grok-4-1-fast-reasoning', displayName: 'Grok 4.1 Fast (Reasoning)' },
      { id: 'grok-4-1-fast-non-reasoning', displayName: 'Grok 4.1 Fast (Instant)' },
      { id: 'grok-3-mini-fast-beta', displayName: 'Grok 3 Mini Fast' },
    ],
  },
  {
    id: 'mistral',
    displayName: 'Mistral',
    baseUrl: 'https://api.mistral.ai/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'mistral-large-2512', displayName: 'Mistral Large 3' },
      { id: 'mistral-medium-2508', displayName: 'Mistral Medium 3.1' },
      { id: 'mistral-small-2506', displayName: 'Mistral Small 3.2' },
      { id: 'magistral-medium-2506', displayName: 'Magistral Medium (reasoning)' },
      { id: 'magistral-small-2506', displayName: 'Magistral Small (reasoning)' },
      { id: 'codestral-2508', displayName: 'Codestral' },
      { id: 'ministral-8b-2512', displayName: 'Ministral 8B' },
      { id: 'ministral-3b-2512', displayName: 'Ministral 3B' },
    ],
  },
  {
    id: 'deepseek',
    displayName: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'deepseek-chat', displayName: 'DeepSeek V3.2' },
      { id: 'deepseek-reasoner', displayName: 'DeepSeek V3.2 Reasoner' },
    ],
  },
  {
    id: 'moonshot',
    displayName: 'Moonshot AI (Kimi)',
    baseUrl: 'https://api.moonshot.ai/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'kimi-k2.5', displayName: 'Kimi K2.5' },
      { id: 'kimi-k2-thinking', displayName: 'Kimi K2 Thinking' },
    ],
  },
  {
    id: 'cohere',
    displayName: 'Cohere',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'command-a-03-2025', displayName: 'Command A' },
      { id: 'command-r-plus-08-2024', displayName: 'Command R+' },
    ],
  },
  {
    id: 'qwen',
    displayName: 'Alibaba (Qwen)',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'qwen3-max', displayName: 'Qwen3 Max' },
      { id: 'qwen-plus', displayName: 'Qwen Plus' },
      { id: 'qwen-turbo', displayName: 'Qwen Turbo' },
      { id: 'qwq-plus', displayName: 'QwQ Plus (reasoning)' },
    ],
  },
  {
    id: 'openrouter',
    displayName: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'openai/gpt-4.1', displayName: 'GPT-4.1' },
      { id: 'anthropic/claude-sonnet-4.6', displayName: 'Claude Sonnet 4.6' },
      { id: 'google/gemini-2.5-flash', displayName: 'Gemini 2.5 Flash' },
      { id: 'mistralai/mistral-large-2512', displayName: 'Mistral Large 3' },
      { id: 'x-ai/grok-3-mini-fast-beta', displayName: 'Grok 3 Mini Fast' },
      { id: 'deepseek/deepseek-chat', displayName: 'DeepSeek V3.2' },
      { id: 'deepseek/deepseek-reasoner', displayName: 'DeepSeek V3.2 Reasoner' },
      { id: 'meta-llama/llama-4-maverick', displayName: 'Llama 4 Maverick' },
      { id: 'meta-llama/llama-4-scout', displayName: 'Llama 4 Scout' },
      { id: 'qwen/qwen3-235b-a22b', displayName: 'Qwen3 235B' },
      { id: 'cohere/command-a-03-2025', displayName: 'Command A' },
    ],
  },
  {
    id: 'ollama',
    displayName: 'Ollama (Local)',
    baseUrl: 'http://localhost:11434/v1',
    requiresApiKey: false,
    isOpenAICompatible: true,
    models: [
      { id: 'llama3.1', displayName: 'Llama 3.1 8B' },
      { id: 'llama4-maverick', displayName: 'Llama 4 Maverick' },
      { id: 'qwen3', displayName: 'Qwen3' },
      { id: 'deepseek-r1', displayName: 'DeepSeek R1' },
      { id: 'mistral', displayName: 'Mistral 7B' },
      { id: 'gemma3', displayName: 'Gemma 3' },
      { id: 'phi4', displayName: 'Phi-4' },
    ],
  },
];

export function getProvider(providerId: string): ProviderInfo | undefined {
  return PROVIDERS.find(p => p.id === providerId);
}
