import type { ProviderInfo } from './types.js';

export const PROVIDERS: ProviderInfo[] = [
  {
    id: 'openai',
    displayName: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'gpt-5.4', displayName: 'GPT-5.4' },
      { id: 'gpt-5.2', displayName: 'GPT-5.2' },
      { id: 'gpt-5.1', displayName: 'GPT-5.1' },
      { id: 'gpt-5', displayName: 'GPT-5' },
      { id: 'gpt-5-mini', displayName: 'GPT-5 Mini' },
      { id: 'gpt-5-nano', displayName: 'GPT-5 Nano' },
      { id: 'gpt-4.1', displayName: 'GPT-4.1' },
      { id: 'gpt-4.1-mini', displayName: 'GPT-4.1 Mini' },
      { id: 'gpt-4.1-nano', displayName: 'GPT-4.1 Nano' },
      { id: 'o4-mini', displayName: 'o4-mini' },
      { id: 'o3', displayName: 'o3' },
    ],
  },
  {
    id: 'anthropic',
    displayName: 'Anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    requiresApiKey: true,
    isOpenAICompatible: false,
    models: [
      { id: 'claude-opus-4-6', displayName: 'Claude Opus 4.6' },
      { id: 'claude-sonnet-4-6', displayName: 'Claude Sonnet 4.6' },
      { id: 'claude-haiku-4-5-20251001', displayName: 'Claude Haiku 4.5' },
    ],
  },
  {
    id: 'google',
    displayName: 'Google (Gemini)',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    requiresApiKey: true,
    isOpenAICompatible: false,
    models: [
      { id: 'gemini-3.1-pro-preview', displayName: 'Gemini 3.1 Pro' },
      { id: 'gemini-3-flash-preview', displayName: 'Gemini 3 Flash' },
      { id: 'gemini-3.1-flash-lite-preview', displayName: 'Gemini 3.1 Flash Lite' },
      { id: 'gemini-2.5-pro', displayName: 'Gemini 2.5 Pro' },
      { id: 'gemini-2.5-flash', displayName: 'Gemini 2.5 Flash' },
      { id: 'gemini-2.5-flash-lite', displayName: 'Gemini 2.5 Flash Lite' },
    ],
  },
  {
    id: 'xai',
    displayName: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'grok-4.20-beta-0309-non-reasoning', displayName: 'Grok 4.20 (Instant)' },
      { id: 'grok-4.20-beta-0309-reasoning', displayName: 'Grok 4.20 (Reasoning)' },
      { id: 'grok-4-1-fast-non-reasoning', displayName: 'Grok 4.1 Fast (Instant)' },
      { id: 'grok-4-1-fast-reasoning', displayName: 'Grok 4.1 Fast (Reasoning)' },
      { id: 'grok-code-fast-1', displayName: 'Grok Code Fast' },
      { id: 'grok-4-fast-reasoning', displayName: 'Grok 4 Fast (Reasoning)' },
      { id: 'grok-4-fast-non-reasoning', displayName: 'Grok 4 Fast (Instant)' },
      { id: 'grok-4-0709', displayName: 'Grok 4' },
      { id: 'grok-3', displayName: 'Grok 3' },
      { id: 'grok-3-mini', displayName: 'Grok 3 Mini' },
    ],
  },
  {
    id: 'mistral',
    displayName: 'Mistral',
    baseUrl: 'https://api.mistral.ai/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'mistral-large-latest', displayName: 'Mistral Large' },
      { id: 'mistral-medium-latest', displayName: 'Mistral Medium' },
      { id: 'mistral-small-latest', displayName: 'Mistral Small' },
      { id: 'magistral-medium-latest', displayName: 'Magistral Medium (Reasoning)' },
      { id: 'magistral-small-latest', displayName: 'Magistral Small (Reasoning)' },
      { id: 'codestral-latest', displayName: 'Codestral' },
    ],
  },
  {
    id: 'deepseek',
    displayName: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'deepseek-chat', displayName: 'DeepSeek V3.2' },
      { id: 'deepseek-reasoner', displayName: 'DeepSeek V3.2 Reasoner' },
    ],
  },
  {
    id: 'moonshot',
    displayName: 'Moonshot AI (Kimi)',
    baseUrl: 'https://api.moonshot.ai/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'kimi-k2.5', displayName: 'Kimi K2.5' },
    ],
  },
  {
    id: 'cohere',
    displayName: 'Cohere',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'command-a-03-2025', displayName: 'Command A' },
      { id: 'command-a-reasoning-08-2025', displayName: 'Command A Reasoning' },
      { id: 'command-r-plus-08-2024', displayName: 'Command R+' },
    ],
  },
  {
    id: 'qwen',
    displayName: 'Alibaba (Qwen)',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    requiresApiKey: true,
    isOpenAICompatible: true,
    models: [
      { id: 'qwen3-max', displayName: 'Qwen3 Max' },
      { id: 'qwen3.5-plus', displayName: 'Qwen3.5 Plus' },
      { id: 'qwen3.5-flash', displayName: 'Qwen3.5 Flash' },
      { id: 'qwen-flash', displayName: 'Qwen Flash' },
      { id: 'qwq-plus', displayName: 'QwQ Plus (Reasoning)' },
    ],
  },
];

export function getProvider(providerId: string): ProviderInfo | undefined {
  return PROVIDERS.find(p => p.id === providerId);
}
